agent:
  action_size: 4
  lr_a: 4e-4
  lr_c: 8e-4
  gamma: 0.99
  entropy_coef: 0.5
  n_hidden: 16
  entropy_decrease: 0.001 # 0.

mediator:
  action_size: 3
  lr_a: 8e-4
  lr_c: 1e-3
  gamma: 0.99
  entropy_coef: 1.0 # 0.5
  n_hidden: 32
  entropy_decrease: 0.002 # 0.

env:
  state_size: 2
  batch_size: 256
  iterations: 10_000
  min_transitions_per_update: 256
  min_episodes_per_update: 5
  eval_episodes: 50
  n_agents: 2

device: "cpu"
name: constraint
