agent:
  action_size: 4  # make "3" to turn mediator off
  lr_a: 4e-4
  lr_c: 8e-4
  gamma: 0.99
  entropy_coef: 3  # 3.5
  n_hidden: 8
  entropy_decrease: 0.0007

mediator:
  action_size: 3
  lr_a: 8e-4
  lr_c: 1e-3
  gamma: 0.99
  entropy_coef: 3
  n_hidden: 32
  entropy_decrease: 0.0007
  reg_weight: 1
  enabled: True

env:
  state_size: 3
  batch_size: 256
  iterations: 10_000
  min_transitions_per_update: 256
  min_episodes_per_update: 5
  eval_episodes: 50
  n_agents: 2
  coef: 0.5

device: "cpu"
name: td-sacrifice
type: test

