agent:
  action_size: 3  # make "2" to turn mediator off
  lr_a: 4e-4 # 4e-4
  lr_c: 8e-4
  gamma: 0.99
  entropy_coef: 2
  n_hidden: 32
  entropy_decrease: 0.0005

mediator:
  action_size: 2
  lr_a: 4e-4 # 4e-4
  lr_c: 8e-4
  gamma: 0.99
  entropy_coef: 2
  n_hidden: 32
  entropy_decrease: 0.0005
  enabled: True

env:
  state_size: 2
  batch_size: 512
  iterations: 10000
  min_transitions_per_update: 512 # same as batch_size
  min_episodes_per_update: 5
  eval_episodes: 50
  n_agents: 2
  horizon: 2

device: "cpu"
name: vanilla
type: test