agent:
  action_size: 3  # make "2" to turn mediator off
  lr_a: 1e-4 # default: 4e-4
  lr_c: 1e-3 # default: 8e-4
  gamma: 0.99
  entropy_coef: 1  # 3.5
  n_hidden: 8
  entropy_decrease: 0.0005

mediator:
  action_size: 2
  lr_a: 1e-4 # default: 8e-4
  lr_c: 1e-3 # default: 1e-3
  gamma: 0.99
  entropy_coef: 1
  n_hidden: 64 # default: 8
  entropy_decrease: 0.0005
  enabled: True

env:
  state_size: 2
  batch_size: 256 # default=128
  iterations: 20000 # default=10000
  min_transitions_per_update: 256 # default=128
  min_episodes_per_update: 256 # default=5
  eval_episodes: 0 # default=50
  n_agents: 2

device: "cpu"
name: vanilla
type: test